version: "3.8"

services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - appnet
    env_file:
      - .env
    command: ["python3", "main.py"]

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=padbdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  appnet:
    driver: bridge
volumes:
  pgdata: