version: "3.8"

services:

  web:
    container_name: web
    build: .
    expose:
      - 8000
    volumes:
      - static_data:/home/app/static
    depends_on:
      - db
    networks:
      - appnet
    command: ["gunicorn", "-w 4", "-b", "0.0.0.0:8000", "app.main:app"]

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=padbdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  appnet:
    driver: bridge
volumes:
  pgdata:
  static_data: